name: Compile Sketches
on:
  push:
    paths:
      - "**.ino"
      - "**.cpp"
      - "**.h"
      - "**LibraryBuild.yml"
jobs:
  build:
    name: Arduino & Digistump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Compile for Arduino
        uses: ArminJo/arduino-test-compile@master
        with:
          arduino-board-fqbn: arduino:avr:uno
          sketch-names: "*.ino"
          sketch-names-find-start: src/projects/arduino/
          build-properties: '{ "WhistleSwitch": "-DDEBUG -DFREQUENCY_RANGE_LOW", "SimpleFrequencyDetector": "-DINFO" }'

      - name: Compile for Digispark
        uses: ArminJo/arduino-test-compile@master
        with:
          required-libraries: DigiKeyboardFr
          platform-url: https://raw.githubusercontent.com/ArminJo/DigistumpArduino/master/package_digistump_index.json
          arduino-board-fqbn: digistump:avr:digispark-tiny
          sketch-names: "*.ino"
          sketch-names-find-start: src/projects/digispark/
          build-properties: '{ "WhistleSwitch": "-DDEBUG -DFREQUENCY_RANGE_LOW", "SimpleFrequencyDetector": "-DINFO" }'
